### ISSUE TITLE
Request: Detailing of possible options in the Options Param

### ISSUE THREAD

**Issue by GeorgeWL** [rudderlabs/rudderstack-docs#24]
it's never really put in detail what possible options there are, or at least not in a clear way.

you get lines like this, with no reference to what possible options there are
> An optional dictionary of information such as context, integrations, etc. Specific user traits can be provided as the context as well

https://github.com/rudderlabs/rudderstack-docs/blob/master/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/README.md#34-track

I think it would be beneficial to detail what can be used on the options object, so can then interface with it more easily.

**Comment by sayan-mitra** [comment]
thanks for the feedback. We will add this.

**Comment by sayan-mitra** [comment]
We have added this to our docs
[Load Options](https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk#3-1-1-load-options)
[Event Level Options](https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk#3-2-1-the-options-parameter)

Please let us know if this helps.

**Comment by GeorgeWL** [comment]
looks perfect to me 👍
